name: Release CI

on:
  # Trigger the workflow on every push to main
  push:
    branches: [main]

  # Trigger workflow manually
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build the app
        run: ./gradlew assembleDebug

  test:
      runs-on: macos-latest
      needs: build
      strategy:
        matrix:
          api-level: [ 24, 28, 29 ,31 ]
          target: [ default ]

      steps:
        - name: Checkout the code
          uses: actions/checkout@v3

        - name: Set up JDK 11
          uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: '11'

        - name: Grant execute permission for gradlew
          run: chmod +x gradlew

        - name: Run unit tests
          run: ./gradlew test --stacktrace

        - name: Run instrumentation tests
          uses: reactivecircus/android-emulator-runner@v2
          with:
            api-level: ${{ matrix.api-level }}
            target: ${{ matrix.target }}
            arch: x86_64
            profile: Nexus 6
            script: ./gradlew connectedCheck

        - name: Upload Reports
          uses: actions/upload-artifact@v2
          with:
            name: Test-Reports
            path: app/build/reports
          if: always()

  distribute:
    name: Distribute app bundle to Play Store
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Version bump
        uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: app/build.gradle
          versionCode: ${{ github.run_number }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Assemble Release Bundle
        run: ./gradlew bundleRelease

      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE }}
          alias: ${{ secrets.TASK_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.TASK_KEY_PASSWORD }}

      - name: Setup authorization with Google Play Store
        run: echo '${{ secrets.GOOGLE_SERVICES_API }}' > service_account.json

      - name: Deploy to alpha
        uses: r0adkll/upload-google-play@v1.0.15
        with:
          serviceAccountJson: service_account.json
          packageName: nl.jovmit.friends
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: internal
          whatsNewDirectory: whatsNewDirectory/
